# defaults file for tripleo_overcloud_deploy
---
openstack_bin: openstack
tripleo_overcloud_deploy_answers_file:
tripleo_overcloud_deploy_baremetal_deployment:
tripleo_overcloud_deploy_config_download: false
tripleo_overcloud_deploy_config_download_timeout:
tripleo_overcloud_deploy_debug: false
tripleo_overcloud_deploy_deployed_server: false
tripleo_overcloud_deploy_deployment_python_interpreter:
tripleo_overcloud_deploy_disable_password_generation: false
tripleo_overcloud_deploy_disable_validations: false
tripleo_overcloud_deploy_dry_run: false
tripleo_overcloud_deploy_environment_dirs: []
tripleo_overcloud_deploy_environment_files: []
tripleo_overcloud_deploy_force_postconfig: false
tripleo_overcloud_deploy_generate_scripts: "{{ tripleo_generate_scripts | default(False) }}"
tripleo_overcloud_deploy_generate_scripts_only: "{{ tripleo_generate_scripts_only | default(False) }}"
tripleo_overcloud_deploy_home_dir: "{{ ansible_env.HOME }}"
tripleo_overcloud_deploy_inflight_validations: false
tripleo_overcloud_deploy_libvirt_type:
tripleo_overcloud_deploy_log: "{{ tripleo_overcloud_deploy_home_dir }}/overcloud_deploy.log"
tripleo_overcloud_deploy_log_combine: true
tripleo_overcloud_deploy_log_output: true
tripleo_overcloud_deploy_networks_file:
tripleo_overcloud_deploy_no_cleanup: false
tripleo_overcloud_deploy_no_config_download: false
tripleo_overcloud_deploy_no_proxy:
tripleo_overcloud_deploy_ntp_server:
tripleo_overcloud_deploy_os_cloud: "{{ tripleo_os_cloud | default('') }}"
tripleo_overcloud_deploy_output_dir:
tripleo_overcloud_deploy_overcloud_ssh_enable_timeout:
tripleo_overcloud_deploy_overcloud_ssh_key:
tripleo_overcloud_deploy_overcloud_ssh_network:
tripleo_overcloud_deploy_overcloud_ssh_port_timeout:
tripleo_overcloud_deploy_overcloud_ssh_user:
tripleo_overcloud_deploy_override_ansible_cfg:
tripleo_overcloud_deploy_plan_environment_file:
tripleo_overcloud_deploy_poll: 10
tripleo_overcloud_deploy_rc_file: "{{ tripleo_rc_file | default(ansible_env.HOME ~ '/stackrc') }}"
tripleo_overcloud_deploy_roles_file:
tripleo_overcloud_deploy_run_validations: false
tripleo_overcloud_deploy_skip_deploy_identifier: false
tripleo_overcloud_deploy_skip_postconfig: false
tripleo_overcloud_deploy_stack: overcloud
tripleo_overcloud_deploy_templates: /usr/share/openstack-tripleo-heat-templates
tripleo_overcloud_deploy_timeout: 5700
tripleo_overcloud_deploy_timeout_arg: 90
tripleo_overcloud_deploy_validation_errors_nonfatal: false
tripleo_overcloud_deploy_validation_warnings_fatal: false
