---
# tasks file for tripleo_container_image_prepare
- name: Setup container image prepare facts
  set_fact:
    _prepare_cmd: >-
      {{ openstack_bin }} tripleo container image prepare
      {{ tripleo_container_image_prepare_environment_files | tripleo.operator.shell_arg_list('--environment-file') }}
      {{ tripleo_container_image_prepare_environment_directory | tripleo.operator.shell_arg_list('--environment-directory') }}
      {{ tripleo_container_image_prepare_roles_file | ternary('--roles-file ' ~ tripleo_container_image_prepare_roles_file, '') }}
      {{ tripleo_container_image_prepare_output_env_file | ternary('--output-env-file ' ~ tripleo_container_image_prepare_output_env_file, '') }}
      {{ tripleo_container_image_prepare_dry_run | ternary('--dry-run', '') }}
      {{ tripleo_container_image_prepare_cleanup | ternary('--cleanup ' ~ tripleo_container_image_prepare_cleanup, '') }}

- name: Show the container image prepare command
  debug:
    var: _prepare_cmd
  when: tripleo_container_image_prepare_debug|bool

- name: Container image prepare
  shell: "{{ _prepare_cmd }}"  # noqa 305
  async: "{{ tripleo_container_image_prepare_timeout }}"
  poll: 1
  become: "{{ tripleo_container_image_prepare_become }}"
  register: tripleo_container_image_prepare_result
  changed_when: true
