# defaults file for tripleo_container_image_build
---
openstack_bin: openstack
tripleo_container_image_build_authfile:
tripleo_container_image_build_base:
tripleo_container_image_build_config_file:
tripleo_container_image_build_config_path:
tripleo_container_image_build_debug: false
tripleo_container_image_build_distro:
tripleo_container_image_build_excludes: []
tripleo_container_image_build_extra_config:
tripleo_container_image_build_generate_scripts_only: "{{ tripleo_generate_scripts_only | default(False) }}"
tripleo_container_image_build_generate_scripts: "{{ tripleo_generate_scripts | default(False) }}"
tripleo_container_image_build_home_dir: "{{ ansible_env.HOME }}"
tripleo_container_image_build_log: "{{ tripleo_container_image_build_home_dir }}/container_image_build.log"
tripleo_container_image_build_log_combine: true
tripleo_container_image_build_log_output: true
tripleo_container_image_build_namespace:
tripleo_container_image_build_poll: 10
tripleo_container_image_build_prefix:
tripleo_container_image_build_push: false
tripleo_container_image_build_registry:
tripleo_container_image_build_rhel_modules: ''
tripleo_container_image_build_skip_build: false
tripleo_container_image_build_tag:
tripleo_container_image_build_timeout: 5700
tripleo_container_image_build_volumes: []
tripleo_container_image_build_work_dir:
tripleo_container_image_build_retries: 0
