---
- name: Converge
  hosts: all
  collections:
    - tripleo.operator
  tasks:

    - name: "Include tripleo_overcloud_node_discover"
      include_role:
        name: "tripleo_overcloud_node_discover"
      vars:
        openstack_bin: echo
        tripleo_overcloud_node_discover_debug: true
        tripleo_os_cloud: undercloud

    - name: Check role
      assert:
        that:
          - tripleo_overcloud_node_discover_output == "overcloud node discover"

    - name: Check parameter "tripleo_overcloud_node_discover_ip"
      include_role:
        name: "tripleo_overcloud_node_discover"
      vars:
        openstack_bin: echo
        tripleo_os_cloud: undercloud
        tripleo_overcloud_node_discover_debug: true
        tripleo_overcloud_node_discover_ip: value

    - name: Assert "tripleo_overcloud_node_discover_ip"
      assert:
        that:
          - tripleo_overcloud_node_discover_output == "overcloud node discover --ip value"

    - name: Check parameter "tripleo_overcloud_node_discover_range"
      include_role:
        name: "tripleo_overcloud_node_discover"
      vars:
        openstack_bin: echo
        tripleo_os_cloud: undercloud
        tripleo_overcloud_node_discover_debug: true
        tripleo_overcloud_node_discover_range: value

    - name: Assert "tripleo_overcloud_node_discover_range"
      assert:
        that:
          - tripleo_overcloud_node_discover_output == "overcloud node discover --range value"

    - name: Check parameter "tripleo_overcloud_node_discover_credentials"
      include_role:
        name: "tripleo_overcloud_node_discover"
      vars:
        openstack_bin: echo
        tripleo_os_cloud: undercloud
        tripleo_overcloud_node_discover_debug: true
        tripleo_overcloud_node_discover_credentials: value

    - name: Assert "tripleo_overcloud_node_discover_credentials"
      assert:
        that:
          - tripleo_overcloud_node_discover_output == "overcloud node discover --credentials value"

    - name: Check parameter "tripleo_overcloud_node_discover_port"
      include_role:
        name: "tripleo_overcloud_node_discover"
      vars:
        openstack_bin: echo
        tripleo_os_cloud: undercloud
        tripleo_overcloud_node_discover_debug: true
        tripleo_overcloud_node_discover_port: value

    - name: Assert "tripleo_overcloud_node_discover_port"
      assert:
        that:
          - tripleo_overcloud_node_discover_output == "overcloud node discover --port value"

    - name: Check parameter "tripleo_overcloud_node_discover_introspect"
      include_role:
        name: "tripleo_overcloud_node_discover"
      vars:
        openstack_bin: echo
        tripleo_os_cloud: undercloud
        tripleo_overcloud_node_discover_debug: true
        tripleo_overcloud_node_discover_introspect: true

    - name: Assert "tripleo_overcloud_node_discover_introspect"
      assert:
        that:
          - tripleo_overcloud_node_discover_output == "overcloud node discover --introspect"

    - name: Check parameter "tripleo_overcloud_node_discover_run_validations"
      include_role:
        name: "tripleo_overcloud_node_discover"
      vars:
        openstack_bin: echo
        tripleo_os_cloud: undercloud
        tripleo_overcloud_node_discover_debug: true
        tripleo_overcloud_node_discover_run_validations: true

    - name: Assert "tripleo_overcloud_node_discover_run_validations"
      assert:
        that:
          - tripleo_overcloud_node_discover_output == "overcloud node discover --run-validations"

    - name: Check parameter "tripleo_overcloud_node_introspect_node_timeout"
      include_role:
        name: "tripleo_overcloud_node_introspect"
      vars:
        openstack_bin: echo
        tripleo_os_cloud: undercloud
        tripleo_overcloud_node_introspect_debug: true
        tripleo_overcloud_node_introspect_node_timeout: value

    - name: Assert "tripleo_overcloud_node_introspect_node_timeout"
      assert:
        that:
          - tripleo_overcloud_node_introspect_output == "overcloud node introspect --node-timeout value"

    - name: Check parameter "tripleo_overcloud_node_introspect_max_retries"
      include_role:
        name: "tripleo_overcloud_node_introspect"
      vars:
        openstack_bin: echo
        tripleo_os_cloud: undercloud
        tripleo_overcloud_node_introspect_debug: true
        tripleo_overcloud_node_introspect_max_retries: value

    - name: Assert "tripleo_overcloud_node_introspect_max_retries"
      assert:
        that:
          - tripleo_overcloud_node_introspect_output == "overcloud node introspect --max-retries value"

    - name: Check parameter "tripleo_overcloud_node_introspect_retry_timeout"
      include_role:
        name: "tripleo_overcloud_node_introspect"
      vars:
        openstack_bin: echo
        tripleo_os_cloud: undercloud
        tripleo_overcloud_node_introspect_debug: true
        tripleo_overcloud_node_introspect_retry_timeout: value

    - name: Assert "tripleo_overcloud_node_introspect_retry_timeout"
      assert:
        that:
          - tripleo_overcloud_node_introspect_output == "overcloud node introspect --retry-timeout value"

    - name: Check parameter "tripleo_overcloud_node_discover_provide"
      include_role:
        name: "tripleo_overcloud_node_discover"
      vars:
        openstack_bin: echo
        tripleo_os_cloud: undercloud
        tripleo_overcloud_node_discover_debug: true
        tripleo_overcloud_node_discover_provide: true

    - name: Assert "tripleo_overcloud_node_discover_provide"
      assert:
        that:
          - tripleo_overcloud_node_discover_output == "overcloud node discover --provide"

    - name: Check parameter "tripleo_overcloud_node_discover_no_deploy_image"
      include_role:
        name: "tripleo_overcloud_node_discover"
      vars:
        openstack_bin: echo
        tripleo_os_cloud: undercloud
        tripleo_overcloud_node_discover_debug: true
        tripleo_overcloud_node_discover_no_deploy_image: true

    - name: Assert "tripleo_overcloud_node_discover_no_deploy_image"
      assert:
        that:
          - tripleo_overcloud_node_discover_output == "overcloud node discover --no-deploy-image"

    - name: Check parameter "tripleo_overcloud_node_discover_instance_boot_option"
      include_role:
        name: "tripleo_overcloud_node_discover"
      vars:
        openstack_bin: echo
        tripleo_os_cloud: undercloud
        tripleo_overcloud_node_discover_debug: true
        tripleo_overcloud_node_discover_instance_boot_option: value

    - name: Assert "tripleo_overcloud_node_discover_instance_boot_option"
      assert:
        that:
          - tripleo_overcloud_node_discover_output == "overcloud node discover --instance-boot-option value"

    - name: Check parameter "tripleo_overcloud_node_discover_concurrency"
      include_role:
        name: "tripleo_overcloud_node_discover"
      vars:
        openstack_bin: echo
        tripleo_os_cloud: undercloud
        tripleo_overcloud_node_discover_debug: true
        tripleo_overcloud_node_discover_concurrency: value

    - name: Assert "tripleo_overcloud_node_discover_concurrency"
      assert:
        that:
          - tripleo_overcloud_node_discover_output == "overcloud node discover --concurrency value"


    - name: Check all parameters for role tripleo_overcloud_node_discover
      include_role:
        name: "tripleo_overcloud_node_discover"
      vars:
        openstack_bin: echo
        tripleo_os_cloud: undercloud
        tripleo_overcloud_node_discover_debug: true
        tripleo_overcloud_node_discover_ip: value
        tripleo_overcloud_node_discover_range: value
        tripleo_overcloud_node_discover_credentials: value
        tripleo_overcloud_node_discover_port: value
        tripleo_overcloud_node_discover_introspect: true
        tripleo_overcloud_node_discover_run_validations: true
        tripleo_overcloud_node_discover_provide: true
        tripleo_overcloud_node_discover_no_deploy_image: true
        tripleo_overcloud_node_discover_instance_boot_option: value
        tripleo_overcloud_node_discover_concurrency: value
        tripleo_overcloud_node_introspect_node_timeout: 60
        tripleo_overcloud_node_introspect_max_retries: 2
        tripleo_overcloud_node_introspect_retry_timeout: 120

    - name: Assert all parameters for role tripleo_overcloud_node_discover
      assert:
        that:
          - tripleo_overcloud_node_discover_output ==
            "overcloud node discover --ip value --range value --credentials value --port value --introspect
            --run-validations --node-timeout 60 --max-retries 2 --retry-timeout 120 --provide --no-deploy-image
            --instance-boot-option value --concurrency value"
