---
# defaults file for tripleo_repos
tripleo_repos_branch: master
tripleo_repos_extra_args: []
tripleo_repos_extra_repos: []
tripleo_repos_repo_base: https://trunk.rdoproject.org
tripleo_repos_version: current-tripleo-dev
