# defaults file for tripleo_overcloud_node_unprovision
---
openstack_bin: openstack
tripleo_overcloud_node_unprovision_all: false
tripleo_overcloud_node_unprovision_debug: false
tripleo_overcloud_node_unprovision_deployment_file:
tripleo_overcloud_node_unprovision_home_dir: "{{ ansible_env.HOME }}"
tripleo_overcloud_node_unprovision_log: "{{ tripleo_overcloud_node_unprovision_home_dir }}/CHANGEME.log"
tripleo_overcloud_node_unprovision_log_combine: true
tripleo_overcloud_node_unprovision_log_output: true
tripleo_overcloud_node_unprovision_os_cloud: "{{ tripleo_os_cloud | default('') }}"
tripleo_overcloud_node_unprovision_poll: 10
tripleo_overcloud_node_unprovision_rc_file: "{{ tripleo_rc_file | default(ansible_env.HOME ~ '/stackrc') }}"
tripleo_overcloud_node_unprovision_stack:
tripleo_overcloud_node_unprovision_timeout: 3600
tripleo_overcloud_node_unprovision_yes: true
tripleo_overcloud_node_unprovision_network_ports:
