---
# defaults file for tripleo_overcloud_upgrade_converge
openstack_bin: openstack
tripleo_overcloud_upgrade_converge_answers_file:
tripleo_overcloud_upgrade_converge_baremetal_deployment:
tripleo_overcloud_upgrade_converge_config_download: false
tripleo_overcloud_upgrade_converge_config_download_timeout:
tripleo_overcloud_upgrade_converge_debug: false
tripleo_overcloud_upgrade_converge_deployed_server: false
tripleo_overcloud_upgrade_converge_disable_password_generation: false
tripleo_overcloud_upgrade_converge_disable_validations: false
tripleo_overcloud_upgrade_converge_dry_run: false
tripleo_overcloud_upgrade_converge_environment_dirs: []
tripleo_overcloud_upgrade_converge_environment_files: []
tripleo_overcloud_upgrade_converge_force_postconfig: false
tripleo_overcloud_upgrade_converge_generate_scripts: "{{ tripleo_generate_scripts | default(False) }}"
tripleo_overcloud_upgrade_converge_generate_scripts_only: "{{ tripleo_generate_scripts_only | default(False) }}"
tripleo_overcloud_upgrade_converge_home_dir: "{{ ansible_env.HOME }}"
tripleo_overcloud_upgrade_converge_inflight_validations: false
tripleo_overcloud_upgrade_converge_libvirt_type:
tripleo_overcloud_upgrade_converge_log: "{{ tripleo_overcloud_upgrade_converge_home_dir }}/overcloud_upgrade_converge.log"
tripleo_overcloud_upgrade_converge_log_combine: true
tripleo_overcloud_upgrade_converge_log_output: true
tripleo_overcloud_upgrade_converge_networks_file:
tripleo_overcloud_upgrade_converge_no_cleanup: false
tripleo_overcloud_upgrade_converge_no_config_download: false
tripleo_overcloud_upgrade_converge_no_proxy:
tripleo_overcloud_upgrade_converge_ntp_server:
tripleo_overcloud_upgrade_converge_os_cloud: "{{ tripleo_os_cloud | default('') }}"
tripleo_overcloud_upgrade_converge_output_dir:
tripleo_overcloud_upgrade_converge_overcloud_ssh_enable_timeout:
tripleo_overcloud_upgrade_converge_overcloud_ssh_key:
tripleo_overcloud_upgrade_converge_overcloud_ssh_network:
tripleo_overcloud_upgrade_converge_overcloud_ssh_port_timeout:
tripleo_overcloud_upgrade_converge_overcloud_ssh_user:
tripleo_overcloud_upgrade_converge_override_ansible_cfg:
tripleo_overcloud_upgrade_converge_plan_environment_file:
tripleo_overcloud_upgrade_converge_poll: 10
tripleo_overcloud_upgrade_converge_rc_file: "{{ tripleo_rc_file | default(ansible_env.HOME ~ '/stackrc') }}"
tripleo_overcloud_upgrade_converge_roles_file:
tripleo_overcloud_upgrade_converge_run_validations: false
tripleo_overcloud_upgrade_converge_skip_deploy_identifier: false
tripleo_overcloud_upgrade_converge_skip_postconfig: false
tripleo_overcloud_upgrade_converge_stack: overcloud
tripleo_overcloud_upgrade_converge_templates: /usr/share/openstack-tripleo-heat-templates
tripleo_overcloud_upgrade_converge_timeout: 5700
tripleo_overcloud_upgrade_converge_timeout_arg: 90
tripleo_overcloud_upgrade_converge_validation_errors_nonfatal: false
tripleo_overcloud_upgrade_converge_validation_warnings_fatal: false
