---
- name: Converge
  hosts: all
  collections:
    - tripleo.operator
  vars:
    openstack_bin: echo
    tripleo_os_cloud: undercloud
    tripleo_overcloud_node_unprovision_log_output: false
    tripleo_overcloud_node_unprovision_poll: 1
    tripleo_overcloud_node_unprovision_debug: true
  tasks:

    - name: "Include tripleo_overcloud_node_unprovision"
      include_role:
        name: "tripleo_overcloud_node_unprovision"

    - name: Check role
      assert:
        that:
          - tripleo_overcloud_node_unprovision_output == "overcloud node unprovision --yes"

    - name: Assert "tripleo_overcloud_node_unprovision_stack"
      include_role:
        name: "tripleo_overcloud_node_unprovision"
      vars:
        tripleo_overcloud_node_unprovision_stack: foo

    - name: Validate tripleo_overcloud_node_unprovision_stack
      assert:
        that:
          - tripleo_overcloud_node_unprovision_output ==
            "overcloud node unprovision --stack foo --yes"

    - name: Assert "tripleo_overcloud_node_unprovision_all"
      include_role:
        name: "tripleo_overcloud_node_unprovision"
      vars:
        tripleo_overcloud_node_unprovision_all: true

    - name: Validate tripleo_overcloud_node_unprovision_all
      assert:
        that:
          - tripleo_overcloud_node_unprovision_output ==
            "overcloud node unprovision --all --yes"

    - name: Assert "tripleo_overcloud_node_unprovision_deployment_file"
      include_role:
        name: "tripleo_overcloud_node_unprovision"
      vars:
        tripleo_overcloud_node_unprovision_deployment_file: foo.yaml

    - name: Validate tripleo_overcloud_node_unprovision_deployment_file
      assert:
        that:
          - tripleo_overcloud_node_unprovision_output ==
            "overcloud node unprovision --yes foo.yaml"

    - name: Assert "tripleo_overcloud_node_unprovision_network_ports"
      include_role:
        name: "tripleo_overcloud_node_unprovision"
      vars:
        tripleo_overcloud_node_unprovision_network_ports: true

    - name: Validate tripleo_overcloud_node_unprovision_network_ports
      assert:
        that:
          - tripleo_overcloud_node_unprovision_output ==
            "overcloud node unprovision --network-ports --yes"
