# defaults file for tripleo_overcloud_node_provision
---
openstack_bin: openstack
tripleo_overcloud_node_provision_concurrency:
tripleo_overcloud_node_provision_debug: false
tripleo_overcloud_node_provision_deployment_file:
tripleo_overcloud_node_provision_generate_scripts: "{{ tripleo_generate_scripts | default(False) }}"
tripleo_overcloud_node_provision_generate_scripts_only: "{{ tripleo_generate_scripts_only | default(False) }}"
tripleo_overcloud_node_provision_home_dir: "{{ ansible_env.HOME }}"
tripleo_overcloud_node_provision_log: "{{ tripleo_overcloud_node_provision_home_dir }}/overcloud_node_provision.log"
tripleo_overcloud_node_provision_log_combine: true
tripleo_overcloud_node_provision_log_output: true
tripleo_overcloud_node_provision_os_cloud: "{{ tripleo_os_cloud | default('') }}"
tripleo_overcloud_node_provision_output_file:
tripleo_overcloud_node_provision_overcloud_ssh_key:
tripleo_overcloud_node_provision_overcloud_ssh_user:
tripleo_overcloud_node_provision_poll: 10
tripleo_overcloud_node_provision_rc_file: "{{ tripleo_rc_file | default(ansible_env.HOME ~ '/stackrc') }}"
tripleo_overcloud_node_provision_stack:
tripleo_overcloud_node_provision_timeout: 3700
tripleo_overcloud_node_provision_timeout_arg:
tripleo_overcloud_node_provision_network_ports:
tripleo_overcloud_node_provision_network_config:
